apiVersion: apps/v1
kind: Deployment
metadata:
  name: trial-deployment
spec:
  replicas: 2  # Set the initial number of replicas to 2
  selector:
    matchLabels:
      app: trial-app
  template:
    metadata:
      labels:
        app: trial-app
    spec:
      containers:
      - name: trial-container
        image: nageshdeshmukh/trial:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: trial-service
spec:
  selector:
    app: trial-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: trial-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: trial-deployment
  minReplicas: 2  # Set the minimum number of replicas to 2
  maxReplicas: 10  # Set the maximum number of replicas to 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # Set the target CPU utilization to 50%
